import { EditorThemeClasses } from 'lexical'

export const theme: EditorThemeClasses = {
    ltr: 'text-left',
    rtl: 'text-right',
    paragraph: 'text-base',
    quote: 'italic text-base border-l-2 border-primary pl-4',
    heading: {
        h1: 'text-5xl font-bold',
        h2: 'text-4xl font-bold',
        h3: 'text-3xl font-bold',
        h4: 'text-2xl font-bold',
        h5: 'text-xl font-bold',
        h6: 'text-lg font-bold',
    },
    list: {
        listitem: 'text-base',
        listitemChecked:
            'relative -ml-6 list-none outline-none before:absolute before:left-0 pl-6 before:top-0.5 before:size-4 before:cursor-pointer before:border before:rounded before:transition before:border-primary/70 before:bg-primary before:text-primary-foreground before:focus:ring-2 before:focus:ring-primary/20 after:absolute after:top-1.5 after:left-1.5 after:border after:border-primary-foreground after:rotate-45 after:w-1 after:h-2 after:border-t-0 after:border-r-2 after:border-b-2 after:border-l-0',
        listitemUnchecked:
            'relative -ml-6 list-none outline-none before:absolute before:left-0 pl-6 before:top-0.5 before:size-4 before:cursor-pointer before:border before:rounded before:border-muted',
        nested: {
            listitem: 'ml-10 list-none before:none after:none',
        },
        olDepth: [
            'list-decimal list-outside ml-6',
            'list-[lower-latin] list-outside',
            'list-[lower-roman] list-outside',
            'list-[upper-roman] list-outside',
            'list-[lower-alpha] list-outside',
        ],
        ul: 'list-disc ml-6',
    },
    hashtag: 'text-blue-500',
    image: 'rounded',
    link: 'text-blue-500 underline',
    text: {
        bold: 'font-bold',
        code: 'font-mono bg-muted px-1 rounded',
        italic: 'italic',
        strikethrough: 'line-through',
        subscript: 'text-subscript',
        superscript: 'text-superscript',
        underline: 'underline',
        underlineStrikethrough: 'underline line-through',
    },
    code: 'bg-gray-200 p-1 rounded',
    codeHighlight: {
        atrule: 'text-rose-500',
        attr: 'text-green-500',
        boolean: 'text-purple-500',
        builtin: 'text-blue-500',
        cdata: 'text-gray-500',
        char: 'text-yellow-500',
        class: 'text-blue-500',
        'class-name': 'text-blue-500',
        comment: 'text-gray-500',
        constant: 'text-purple-500',
        deleted: 'text-red-500',
        doctype: 'text-gray-500',
        entity: 'text-red-500',
        function: 'text-blue-500',
        important: 'text-yellow-500',
        inserted: 'text-green-500',
        keyword: 'text-blue-500',
        namespace: 'text-yellow-500',
        number: 'text-purple-500',
        operator: 'text-red-500',
        prolog: 'text-gray-500',
        property: 'text-green-500',
        punctuation: 'text-gray-500',
        regex: 'text-yellow-500',
        selector: 'text-blue-500',
        string: 'text-green-500',
        symbol: 'text-yellow-500',
        tag: 'text-blue-500',
        url: 'text-blue-500',
        variable: 'text-purple-500',
    },
    table: 'w-full table-auto border-collapse border border-muted',
    tableRow: 'border-b border-muted',
    tableCell: 'p-2 border border-muted',
    tableResizeRuler: 'h-0.5 bg-muted',
    tableCellResizer: 'w-0.5 bg-muted',
}
